name: Run Playwright Tests

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2 # Update from v1 to v2
        with:
          node-version: '16.x' # Update to use Node.js 16.x
      - name: Install Dependencies
        run: npm install
      - name: Run Playwright Tests
        run: npm test
